name: SMPRankPoints
version: '1.1'
main: ch.ksrminecraft.sMPRankPoints.SMPRankPoints
api-version: '1.21'
authors: [ksrminecraft-tecs]
description: Vergibt automatisch globale Rangpunkte für Aktionen im SMP

commands:
  srpreload:
    description: Lädt die Konfiguration des Plugins neu
    usage: /srpreload
    permission: smprankpoints.admin

  resetadvancements:
    description: Setzt alle Advancements eines Spielers zurück
    usage: /resetadvancements <Spieler>
    permission: smprankpoints.resetadvancements
