name: SMPRankPoints
version: '1.0-SNAPSHOT'
main: ch.ksrminecraft.sMPRankPoints.SMPRankPoints
api-version: '1.21'
authors: [ Timy Liniger ]
description: writes rankpoint to global DB
website: https://ksrminecraft.ch/
