name: SMPRankPoints
version: '1.0-SNAPSHOT'
main: ch.ksrminecraft.sMPRankPoints.SMPRankPoints
api-version: '1.21'
authors: [ksrminecaft-tecs]
description: writes rankpoints to global DB
softdepend: [RangAPI]
commands:
  apreload:
    description: Lädt die Config neu
    permission: smprankpoints.admin
  points:
    description: Zeigt Punktestand an
    permission: smprankpoints.points
    usage: /points [spieler]
